// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DeviceInfoModal: typeof import('./src/components/device-info-modal/index.vue')['default']
    JxDot: typeof import('./src/components/jx-dot/index.vue')['default']
    JxIcon: typeof import('./src/components/jx-icon/index.vue')['default']
    JxNavBar: typeof import('./src/components/jx-nav-bar/index.vue')['default']
    JxScrollView: typeof import('./src/components/jx-scroll-view/index.vue')['default']
    JxTabBar: typeof import('./src/components/jx-tab-bar/index.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutBacktop: typeof import('@nutui/nutui-taro')['Backtop']
    NutBadge: typeof import('@nutui/nutui-taro')['Badge']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCascader: typeof import('@nutui/nutui-taro')['Cascader']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutElevator: typeof import('@nutui/nutui-taro')['Elevator']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopover: typeof import('@nutui/nutui-taro')['Popover']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
