// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DeviceInfoModal: typeof import('./src/components/device-info-modal/index.vue')['default']
    JxDot: typeof import('./src/components/jx-dot/index.vue')['default']
    JxNavBar: typeof import('./src/components/jx-nav-bar/index.vue')['default']
    JxTabBar: typeof import('./src/components/jx-tab-bar/index.vue')['default']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
  }
}
